// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp_lJJrZey8bl3kV6mP7ByDas0S9qhdmY',
    appId: '1:172681571826:web:84e077ca9c40c9f16b8f6b',
    messagingSenderId: '172681571826',
    projectId: 'qflow-353dd',
    authDomain: 'qflow-353dd.firebaseapp.com',
    storageBucket: 'qflow-353dd.firebasestorage.app',
    measurementId: 'G-Z0V18RRDWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOZe155cw-EPeNPx5HaQsmtK-efoPj9So',
    appId: '1:172681571826:android:5ca0f8ccb413f6a46b8f6b',
    messagingSenderId: '172681571826',
    projectId: 'qflow-353dd',
    storageBucket: 'qflow-353dd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp_lJJrZey8bl3kV6mP7ByDas0S9qhdmY',
    appId: '1:172681571826:web:cbb0dc69178b46426b8f6b',
    messagingSenderId: '172681571826',
    projectId: 'qflow-353dd',
    authDomain: 'qflow-353dd.firebaseapp.com',
    storageBucket: 'qflow-353dd.firebasestorage.app',
    measurementId: 'G-70KNZJFCQC',
  );
}
